name: bs_overlay_example
description: "BSOverlay showcase example - part of BSLibrary"
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  dartx: 1.2.0
  bs_overlay:
    git:
      url: https://github.com/B-Saeid/bs_library.git
      path: bs_overlay
  bs_widgets:
    git:
      url: https://github.com/B-Saeid/bs_library.git
      path: bs_widgets
  bs_styles:
    git:
      url: https://github.com/B-Saeid/bs_library.git
      path: bs_styles

  # You only need these if you opt in to use LiveData
  #  flutter_riverpod: 3.0.3
  #  bs_ref_query:
  #    git:
  #      url: https://github.com/B-Saeid/bs_library.git
  #      path: bs_ref_query

  cupertino_icons: 1.0.8
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 6.0.0
