name: bs_widgets
description: "A new Flutter package project."
version: 0.0.1
homepage: https://bsaeid.dev/
#repository: https://github.com/B-Saeid/bs_widgets
#issue_tracker: https://github.com/ueman/bs_widgets/issues
publish_to: none


environment:
  sdk: ^3.10.1
  flutter: ">=1.17.0"

dependencies:
  bs_utils:
    path: ../bs_utils
  bs_l10n:
    path: ../bs_l10n
  bs_ref_query:
    path: ../bs_ref_query
  bs_internet_service:
    path: ../bs_internet_service
  bs_styles:
    path: ../bs_styles
  flutter:
    sdk: flutter
  flutter_riverpod: 3.0.3
  lottie: 3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
