name: bs_feedback
description: "Package that allows the user to give interactive feedback directly in the app"
version: 0.0.1
homepage: https://bsaeid.dev/
repository: https://github.com/B-Saeid/bs_library/tree/main/bs_feedback
issue_tracker: https://github.com/B-Saeid/bs_library/issues
publish_to: none


environment:
  sdk: ^3.10.1
  flutter: ">=1.17.0"

dependencies:
  bs_utils:
    git:
      url: https://github.com/B-Saeid/bs_library.git
      path: bs_utils
  bs_l10n:
    git:
      url: https://github.com/B-Saeid/bs_library.git
      path: bs_l10n
  bs_ref_query:
    git:
      url: https://github.com/B-Saeid/bs_library.git
      path: bs_ref_query
  bs_widgets:
    git:
      url: https://github.com/B-Saeid/bs_library.git
      path: bs_widgets
  bs_toast:
    git:
      url: https://github.com/B-Saeid/bs_library.git
      path: bs_toast
  bs_overlay:
    git:
      url: https://github.com/B-Saeid/bs_library.git
      path: bs_overlay
  bs_styles:
    git:
      url: https://github.com/B-Saeid/bs_library.git
      path: bs_styles

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  collection: 1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
