name: bs_ref_query
description: "A MediaQuery alternative riverpod-based lookup system using either `WidgetRef` or `Ref`"
version: 0.0.1
homepage: https://bsaeid.dev/
repository: https://github.com/B-Saeid/bs_library/tree/main/bs_ref_query
issue_tracker: https://github.com/B-Saeid/bs_library/issues
publish_to: none

environment:
  sdk: ^3.10.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  bs_utils:
    git:
      url: https://github.com/B-Saeid/bs_library.git
      path: bs_utils
  bs_riverpod_utils:
    git:
      url: https://github.com/B-Saeid/bs_library.git
      path: bs_riverpod_utils
  flutter_riverpod: 3.0.3
  riverpod_annotation: 3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: 3.0.3
  build_runner: 2.10.4