name: bs_timeago
description: "Fork of timeago packages packed with utility widgets and improvements"
version: 0.0.1
homepage: https://bsaeid.dev
#repository: https://github.com/B-Saeid/bs_timeago
#issue_tracker: https://github.com/ueman/bs_timeago/issues
environment:
  sdk: ^3.10.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: 0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0